/**
 * Tests for YouTube transcript fetcher with mocked HTTP responses
 */

import { describe, test, expect, afterEach } from 'bun:test';
import { fetchTranscript, extractVideoId } from '../src/lib/fetcher';

const originalFetch = globalThis.fetch;

function createMockFetch(handler: (url: string, init?: RequestInit) => Promise<Response>) {
  const mockFn = async (input: string | URL | Request, init?: RequestInit) => {
    const url =
      typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    return handler(url, init);
  };
  (mockFn as typeof fetch).preconnect = () => {};
  return mockFn as typeof fetch;
}

function makeWatchPageHTML(opts: {
  apiKey?: string;
  captionTracks?: object[];
} = {}): string {
  const { apiKey = 'AIzaSyFakeKey123', captionTracks = [] } = opts;
  const playerResponse = {
    captions: { playerCaptionsTracklistRenderer: { captionTracks } },
  };
  return [
    '<html><head>',
    `<script>var ytcfg = {}; ytcfg.set({"INNERTUBE_API_KEY":"${apiKey}","DATA_SYNC_ID":"test"});</script>`,
    '</head><body>',
    `<script>var ytInitialPlayerResponse = ${JSON.stringify(playerResponse)};</script>`,
    '</body></html>',
  ].join('');
}

function makeAndroidPlayerResponse(captionTracks: object[]) {
  return {
    playabilityStatus: { status: 'OK' },
    captions: { playerCaptionsTracklistRenderer: { captionTracks } },
  };
}

const ANDROID_TRACKS = [
  {
    baseUrl: 'https://www.youtube.com/api/timedtext?v=test123&lang=en&kind=asr',
    languageCode: 'en',
    kind: 'asr',
    name: { simpleText: 'English (auto-generated)' },
  },
];

const DEFAULT_CAPTION_EVENTS = {
  events: [
    { segs: [{ utf8: 'Hello ' }, { utf8: 'world' }], tStartMs: 0, dDurationMs: 2000 },
    { segs: [{ utf8: 'This is a test' }], tStartMs: 2000, dDurationMs: 3000 },
  ],
};

describe('fetchTranscript', () => {
  afterEach(() => {
    globalThis.fetch = originalFetch;
  });

  test('fetches transcript via ANDROID innertube client', async () => {
    let androidCallMade = false;

    globalThis.fetch = createMockFetch(async (url, init) => {
      if (url.includes('youtube.com/watch')) {
        return new Response(makeWatchPageHTML(), { status: 200 });
      }
      if (url.includes('youtubei/v1/player')) {
        androidCallMade = true;
        const body = JSON.parse((init?.body as string) || '{}');
        expect(body.context.client.clientName).toBe('ANDROID');
        return new Response(JSON.stringify(makeAndroidPlayerResponse(ANDROID_TRACKS)), { status: 200 });
      }
      if (url.includes('timedtext')) {
        return new Response(JSON.stringify(DEFAULT_CAPTION_EVENTS), { status: 200 });
      }
      return new Response('Not found', { status: 404 });
    });

    const transcript = await fetchTranscript('test123');
    expect(transcript.videoId).toBe('test123');
    expect(transcript.language).toBe('en');
    expect(transcript.isAutoGenerated).toBe(true);
    expect(transcript.text).toBe('Hello world This is a test');
    expect(transcript.segments).toHaveLength(2);
    expect(androidCallMade).toBe(true);
  });

  test('innertube URL includes API key from watch page', async () => {
    let innertubeUrl = '';

    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) {
        return new Response(makeWatchPageHTML({ apiKey: 'AIzaSyRealKey456' }), { status: 200 });
      }
      if (url.includes('youtubei/v1/player')) {
        innertubeUrl = url;
        return new Response(JSON.stringify(makeAndroidPlayerResponse(ANDROID_TRACKS)), { status: 200 });
      }
      return new Response(JSON.stringify(DEFAULT_CAPTION_EVENTS), { status: 200 });
    });

    await fetchTranscript('test123');
    expect(innertubeUrl).toContain('key=AIzaSyRealKey456');
  });

  test('uses ANDROID user-agent for innertube call', async () => {
    let innertubeUA = '';

    globalThis.fetch = createMockFetch(async (url, init) => {
      if (url.includes('youtube.com/watch')) {
        return new Response(makeWatchPageHTML(), { status: 200 });
      }
      if (url.includes('youtubei/v1/player')) {
        innertubeUA = (init?.headers as Record<string, string>)?.['User-Agent'] || '';
        return new Response(JSON.stringify(makeAndroidPlayerResponse(ANDROID_TRACKS)), { status: 200 });
      }
      return new Response(JSON.stringify(DEFAULT_CAPTION_EVENTS), { status: 200 });
    });

    await fetchTranscript('test123');
    expect(innertubeUA).toContain('Android');
  });

  test('falls back to ytInitialPlayerResponse when ANDROID innertube fails', async () => {
    const htmlTracks = [
      { baseUrl: 'https://example.com/html-track', languageCode: 'en', kind: 'asr' },
    ];

    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) {
        return new Response(makeWatchPageHTML({ captionTracks: htmlTracks }), { status: 200 });
      }
      if (url.includes('youtubei/v1/player')) {
        return new Response(JSON.stringify({ playabilityStatus: { status: 'UNPLAYABLE' } }), { status: 200 });
      }
      return new Response(JSON.stringify(DEFAULT_CAPTION_EVENTS), { status: 200 });
    });

    const transcript = await fetchTranscript('test123');
    expect(transcript.language).toBe('en');
  });

  test('falls back to ytInitialPlayerResponse when no API key in page', async () => {
    const htmlTracks = [
      { baseUrl: 'https://example.com/no-key-track', languageCode: 'en' },
    ];
    const pageHtml = [
      '<html><body>',
      `<script>var ytInitialPlayerResponse = ${JSON.stringify({ captions: { playerCaptionsTracklistRenderer: { captionTracks: htmlTracks } } })};</script>`,
      '</body></html>',
    ].join('');

    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) return new Response(pageHtml, { status: 200 });
      if (url.includes('youtubei')) throw new Error('Should not call innertube without key');
      return new Response(JSON.stringify(DEFAULT_CAPTION_EVENTS), { status: 200 });
    });

    const transcript = await fetchTranscript('test123');
    expect(transcript.language).toBe('en');
  });

  test('throws when all sources return no captions', async () => {
    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) {
        return new Response(makeWatchPageHTML({ captionTracks: [] }), { status: 200 });
      }
      if (url.includes('youtubei/v1/player')) {
        return new Response(JSON.stringify({ playabilityStatus: { status: 'UNPLAYABLE' } }), { status: 200 });
      }
      return new Response('Not found', { status: 404 });
    });

    await expect(fetchTranscript('test123')).rejects.toThrow('No captions available');
  });

  test('throws when watch page fails', async () => {
    globalThis.fetch = createMockFetch(async () => {
      return new Response('Server error', { status: 500 });
    });

    await expect(fetchTranscript('test123')).rejects.toThrow('No captions available');
  });

  test('respects language preference', async () => {
    const tracks = [
      { baseUrl: 'https://example.com/en', languageCode: 'en' },
      { baseUrl: 'https://example.com/es', languageCode: 'es' },
    ];
    const mockCaptionResponse = {
      events: [{ segs: [{ utf8: 'Hola mundo' }], tStartMs: 0, dDurationMs: 1000 }],
    };

    let captionUrlCalled = '';
    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) return new Response(makeWatchPageHTML(), { status: 200 });
      if (url.includes('youtubei/v1/player')) return new Response(JSON.stringify(makeAndroidPlayerResponse(tracks)), { status: 200 });
      captionUrlCalled = url;
      return new Response(JSON.stringify(mockCaptionResponse), { status: 200 });
    });

    const transcript = await fetchTranscript('test123', { languages: ['es', 'en'] });
    expect(transcript.language).toBe('es');
    expect(captionUrlCalled).toContain('example.com/es');
  });

  test('prefers manual captions over auto-generated', async () => {
    const tracks = [
      { baseUrl: 'https://example.com/auto', languageCode: 'en', kind: 'asr' },
      { baseUrl: 'https://example.com/manual', languageCode: 'en' },
    ];
    const mockCaptionResponse = { events: [{ segs: [{ utf8: 'Manual caption' }], tStartMs: 0, dDurationMs: 1000 }] };

    let captionUrlCalled = '';
    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) return new Response(makeWatchPageHTML(), { status: 200 });
      if (url.includes('youtubei/v1/player')) return new Response(JSON.stringify(makeAndroidPlayerResponse(tracks)), { status: 200 });
      captionUrlCalled = url;
      return new Response(JSON.stringify(mockCaptionResponse), { status: 200 });
    });

    const transcript = await fetchTranscript('test123', { languages: ['en'] });
    expect(transcript.isAutoGenerated).toBe(false);
    expect(captionUrlCalled).toContain('example.com/manual');
  });

  test('excludes auto-generated when option is false', async () => {
    const tracks = [{ baseUrl: 'https://example.com/auto', languageCode: 'en', kind: 'asr' }];

    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) return new Response(makeWatchPageHTML(), { status: 200 });
      if (url.includes('youtubei/v1/player')) return new Response(JSON.stringify(makeAndroidPlayerResponse(tracks)), { status: 200 });
      return new Response('', { status: 200 });
    });

    await expect(
      fetchTranscript('test123', { languages: ['en'], includeAutoGenerated: false })
    ).rejects.toThrow('No suitable caption track found');
  });

  test('throws when caption track is empty', async () => {
    const tracks = [{ baseUrl: 'https://example.com/en', languageCode: 'en' }];

    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) return new Response(makeWatchPageHTML(), { status: 200 });
      if (url.includes('youtubei/v1/player')) return new Response(JSON.stringify(makeAndroidPlayerResponse(tracks)), { status: 200 });
      return new Response(JSON.stringify({ events: [] }), { status: 200 });
    });

    await expect(fetchTranscript('test123')).rejects.toThrow('Caption track is empty');
  });

  test('handles events without segs field', async () => {
    const tracks = [{ baseUrl: 'https://example.com/en', languageCode: 'en' }];
    const mockCaptionResponse = {
      events: [
        { tStartMs: 0, dDurationMs: 1000 },
        { segs: [{ utf8: 'Valid text' }], tStartMs: 1000, dDurationMs: 2000 },
        { segs: [], tStartMs: 3000, dDurationMs: 1000 },
      ],
    };

    globalThis.fetch = createMockFetch(async (url) => {
      if (url.includes('youtube.com/watch')) return new Response(makeWatchPageHTML(), { status: 200 });
      if (url.includes('youtubei/v1/player')) return new Response(JSON.stringify(makeAndroidPlayerResponse(tracks)), { status: 200 });
      return new Response(JSON.stringify(mockCaptionResponse), { status: 200 });
    });

    const transcript = await fetchTranscript('test123');
    expect(transcript.segments).toHaveLength(1);
    expect(transcript.segments[0].text).toBe('Valid text');
  });
});

describe('extractVideoId edge cases', () => {
  test('handles music URL', () => {
    expect(extractVideoId('https://music.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  test('handles URL with extra path segments', () => {
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ/')).toBe('dQw4w9WgXcQ');
  });

  test('rejects video ID with wrong length', () => {
    expect(extractVideoId('abc')).toBeNull();
    expect(extractVideoId('abcdefghijkl')).toBeNull();
  });

  test('rejects video ID with invalid characters', () => {
    expect(extractVideoId('abc!@#$%^&*()')).toBeNull();
  });
});
