/**
 * Tests for ytranscript
 */

import { describe, test, expect } from 'bun:test';
import { extractVideoId } from '../src/lib/fetcher';
import { formatSrt, formatVtt, formatText } from '../src/outputs';
import type { Transcript } from '../src/types';

describe('extractVideoId', () => {
  test('extracts from plain video ID', () => {
    expect(extractVideoId('dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  test('extracts from youtube.com watch URL', () => {
    expect(extractVideoId('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://youtube.com/watch?v=dQw4w9WgXcQ&t=100')).toBe('dQw4w9WgXcQ');
  });

  test('extracts from youtu.be short URL', () => {
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
    expect(extractVideoId('https://youtu.be/dQw4w9WgXcQ?t=100')).toBe('dQw4w9WgXcQ');
  });

  test('extracts from embed URL', () => {
    expect(extractVideoId('https://www.youtube.com/embed/dQw4w9WgXcQ')).toBe('dQw4w9WgXcQ');
  });

  test('returns null for invalid input', () => {
    expect(extractVideoId('not-a-video-id')).toBeNull();
    expect(extractVideoId('https://example.com')).toBeNull();
    expect(extractVideoId('')).toBeNull();
  });
});

describe('output formatters', () => {
  const mockTranscript: Transcript = {
    videoId: 'test123',
    text: 'Hello world This is a test',
    language: 'en',
    isAutoGenerated: false,
    segments: [
      { text: 'Hello world', start: 0, duration: 2.5 },
      { text: 'This is a test', start: 2.5, duration: 3 },
    ],
  };

  test('formatSrt creates valid SRT', () => {
    const srt = formatSrt(mockTranscript);
    expect(srt).toContain('1\n00:00:00,000 --> 00:00:02,500\nHello world');
    expect(srt).toContain('2\n00:00:02,500 --> 00:00:05,500\nThis is a test');
  });

  test('formatVtt creates valid VTT', () => {
    const vtt = formatVtt(mockTranscript);
    expect(vtt).toStartWith('WEBVTT');
    expect(vtt).toContain('00:00:00.000 --> 00:00:02.500');
    expect(vtt).toContain('Hello world');
  });

  test('formatText returns plain text', () => {
    const text = formatText(mockTranscript);
    expect(text).toBe('Hello world This is a test');
  });

  test('formatText with timestamps', () => {
    const text = formatText(mockTranscript, true);
    expect(text).toContain('[0:00] Hello world');
    expect(text).toContain('[0:02] This is a test');
  });
});
