/**
 * Tests for newly extracted/exported pure helpers across modules.
 *
 * These functions have no side effects and no external dependencies — they are
 * the safest, most useful units to test in isolation.
 */

import { describe, test, expect } from 'bun:test';

import {
  extractApiKey,
  extractTracksFromHTML,
  parseTimedTextEvents,
  selectCaptionTrack,
  type CaptionTrack,
} from '../src/lib/fetcher';
import { chunk, selectUnprocessed } from '../src/lib/processor';
import {
  escapeCsvCell,
  formatSrtTime,
  formatTimestamp,
  formatVttTime,
  pad,
  resultToCsvRow,
  rowToCsv,
  splitTime,
} from '../src/outputs';
import { extractIdFromJsonlRecord } from '../src/loaders';
import { extractVideoIdFromUrl } from '../src/loaders/history';
import { parseCSV, parseCSVLine } from '../src/loaders/watchLater';
import { formatTranscriptForCli, validateProxyUrl } from '../src/cli-helpers';
import { formatTranscriptForMcp } from '../src/mcp-helpers';
import type { Transcript, WatchHistoryMeta } from '../src/types';

const sampleTranscript: Transcript = {
  videoId: 'abc12345678',
  text: 'Hello world',
  language: 'en',
  isAutoGenerated: false,
  segments: [
    { text: 'Hello world', start: 0, duration: 2 },
    { text: 'Second seg', start: 2, duration: 3 },
  ],
};

// ---------------------------------------------------------------------------
// fetcher pure helpers
// ---------------------------------------------------------------------------

describe('extractApiKey', () => {
  test('extracts API key from inline JSON config', () => {
    const html = '<script>"INNERTUBE_API_KEY":"AIzaSyABC123"</script>';
    expect(extractApiKey(html)).toBe('AIzaSyABC123');
  });

  test('tolerates whitespace around the colon', () => {
    const html = '"INNERTUBE_API_KEY"   :   "AIzaSyXYZ"';
    expect(extractApiKey(html)).toBe('AIzaSyXYZ');
  });

  test('returns null when key not present', () => {
    expect(extractApiKey('<html></html>')).toBeNull();
  });
});

describe('extractTracksFromHTML', () => {
  test('extracts captionTracks from ytInitialPlayerResponse', () => {
    const playerResponse = {
      captions: {
        playerCaptionsTracklistRenderer: {
          captionTracks: [
            { baseUrl: 'https://example.com/en', languageCode: 'en' },
          ],
        },
      },
    };
    const html = `<script>var ytInitialPlayerResponse = ${JSON.stringify(playerResponse)};</script>`;
    const tracks = extractTracksFromHTML(html);
    expect(tracks).not.toBeNull();
    expect(tracks?.[0].languageCode).toBe('en');
  });

  test('returns null when no playerResponse block exists', () => {
    expect(extractTracksFromHTML('<html></html>')).toBeNull();
  });

  test('returns null when captionTracks is empty', () => {
    const html =
      '<script>var ytInitialPlayerResponse = {"captions":{"playerCaptionsTracklistRenderer":{"captionTracks":[]}}};</script>';
    expect(extractTracksFromHTML(html)).toBeNull();
  });

  test('returns null when JSON is malformed', () => {
    const html = '<script>var ytInitialPlayerResponse = {bad json};</script>';
    expect(extractTracksFromHTML(html)).toBeNull();
  });
});

describe('selectCaptionTrack', () => {
  const tracks: CaptionTrack[] = [
    { baseUrl: 'u-auto-en', languageCode: 'en', kind: 'asr' },
    { baseUrl: 'u-manual-en', languageCode: 'en' },
    { baseUrl: 'u-manual-es', languageCode: 'es' },
  ];

  test('prefers manual over auto-generated for the same language', () => {
    const selected = selectCaptionTrack(tracks, ['en'], true);
    expect(selected?.baseUrl).toBe('u-manual-en');
  });

  test('honors language order', () => {
    const selected = selectCaptionTrack(tracks, ['es', 'en'], true);
    expect(selected?.languageCode).toBe('es');
  });

  test('excludes auto when includeAutoGenerated is false', () => {
    const onlyAuto: CaptionTrack[] = [{ baseUrl: 'u', languageCode: 'en', kind: 'asr' }];
    expect(selectCaptionTrack(onlyAuto, ['en'], false)).toBeNull();
  });

  test('falls back to first available track when no language matches', () => {
    const selected = selectCaptionTrack(tracks, ['fr'], true);
    expect(selected?.baseUrl).toBe('u-manual-en');
  });

  test('matches language prefix (en matches en-US)', () => {
    const localized: CaptionTrack[] = [{ baseUrl: 'u', languageCode: 'en-US' }];
    expect(selectCaptionTrack(localized, ['en'], true)?.languageCode).toBe('en-US');
  });

  test('returns null for empty track list', () => {
    expect(selectCaptionTrack([], ['en'], true)).toBeNull();
  });
});

describe('parseTimedTextEvents', () => {
  test('joins segs into a single string per event', () => {
    const segments = parseTimedTextEvents({
      events: [
        { segs: [{ utf8: 'Hello ' }, { utf8: 'world' }], tStartMs: 0, dDurationMs: 1500 },
      ],
    });
    expect(segments).toEqual([{ text: 'Hello world', start: 0, duration: 1.5 }]);
  });

  test('skips events without segs and empty segments', () => {
    const segments = parseTimedTextEvents({
      events: [
        { tStartMs: 0, dDurationMs: 1000 },
        { segs: [{ utf8: '   ' }], tStartMs: 1000, dDurationMs: 1000 },
        { segs: [{ utf8: 'kept' }], tStartMs: 2000, dDurationMs: 1000 },
      ],
    });
    expect(segments).toHaveLength(1);
    expect(segments[0].text).toBe('kept');
  });

  test('handles empty/missing events array', () => {
    expect(parseTimedTextEvents({})).toEqual([]);
    expect(parseTimedTextEvents({ events: [] })).toEqual([]);
  });

  test('handles missing timing fields gracefully', () => {
    const [seg] = parseTimedTextEvents({ events: [{ segs: [{ utf8: 'no time' }] }] });
    expect(seg).toEqual({ text: 'no time', start: 0, duration: 0 });
  });
});

// ---------------------------------------------------------------------------
// processor pure helpers
// ---------------------------------------------------------------------------

describe('chunk', () => {
  test('splits into batches of the given size', () => {
    expect(chunk([1, 2, 3, 4, 5], 2)).toEqual([[1, 2], [3, 4], [5]]);
  });

  test('returns a single batch when size exceeds length', () => {
    expect(chunk([1, 2], 10)).toEqual([[1, 2]]);
  });

  test('handles empty input', () => {
    expect(chunk([], 3)).toEqual([]);
  });

  test('size <= 0 returns the input as a single batch', () => {
    expect(chunk([1, 2, 3], 0)).toEqual([[1, 2, 3]]);
  });
});

describe('selectUnprocessed', () => {
  const videos: WatchHistoryMeta[] = [
    { videoId: 'a', source: 'manual' },
    { videoId: 'b', source: 'manual' },
    { videoId: 'c', source: 'manual' },
  ];

  test('filters out IDs already in the skip set', () => {
    const result = selectUnprocessed(videos, new Set(['a', 'c']));
    expect(result.map((v) => v.videoId)).toEqual(['b']);
  });

  test('returns the original array when skip set is empty', () => {
    expect(selectUnprocessed(videos, new Set())).toBe(videos);
  });

  test('returns empty when everything is skipped', () => {
    expect(selectUnprocessed(videos, new Set(['a', 'b', 'c']))).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// outputs pure helpers
// ---------------------------------------------------------------------------

describe('pad', () => {
  test('left-pads with zeros', () => {
    expect(pad(5, 3)).toBe('005');
    expect(pad(123, 2)).toBe('123');
    expect(pad(0, 2)).toBe('00');
  });
});

describe('splitTime', () => {
  test('decomposes seconds into HMS parts', () => {
    expect(splitTime(3661.5)).toEqual({ hours: 1, minutes: 1, seconds: 1, ms: 500 });
  });

  test('handles zero', () => {
    expect(splitTime(0)).toEqual({ hours: 0, minutes: 0, seconds: 0, ms: 0 });
  });
});

describe('formatSrtTime', () => {
  test('uses comma as ms separator', () => {
    expect(formatSrtTime(2.5)).toBe('00:00:02,500');
  });

  test('formats multi-hour timestamps', () => {
    expect(formatSrtTime(3661.5)).toBe('01:01:01,500');
  });
});

describe('formatVttTime', () => {
  test('uses period as ms separator', () => {
    expect(formatVttTime(2.5)).toBe('00:00:02.500');
  });
});

describe('formatTimestamp', () => {
  test('produces a short M:SS format', () => {
    expect(formatTimestamp(0)).toBe('0:00');
    expect(formatTimestamp(65)).toBe('1:05');
    expect(formatTimestamp(3600)).toBe('60:00');
  });
});

describe('escapeCsvCell', () => {
  test('wraps value in quotes', () => {
    expect(escapeCsvCell('hello')).toBe('"hello"');
  });

  test('doubles embedded quotes', () => {
    expect(escapeCsvCell('say "hi"')).toBe('"say ""hi"""');
  });

  test('handles null/undefined as empty string', () => {
    expect(escapeCsvCell(null)).toBe('""');
    expect(escapeCsvCell(undefined)).toBe('""');
  });

  test('coerces non-strings via String()', () => {
    expect(escapeCsvCell(42)).toBe('"42"');
    expect(escapeCsvCell(true)).toBe('"true"');
  });
});

describe('rowToCsv', () => {
  test('joins escaped cells with commas', () => {
    expect(rowToCsv(['a', 'b', 'c'])).toBe('"a","b","c"');
  });

  test('escapes quotes per cell', () => {
    expect(rowToCsv(['ok', 'q"u"ote'])).toBe('"ok","q""u""ote"');
  });
});

describe('resultToCsvRow', () => {
  test('extracts successful row', () => {
    const row = resultToCsvRow({
      meta: {
        videoId: 'v1',
        source: 'manual',
        title: 'T',
        url: 'U',
        channel: { name: 'C' },
        watchedAt: 'W',
      },
      transcript: {
        videoId: 'v1',
        text: 'hello',
        language: 'en',
        isAutoGenerated: true,
        segments: [],
      },
    });
    expect(row).toEqual(['v1', 'manual', 'T', 'U', 'C', 'W', 'en', 'true', 'hello', '']);
  });

  test('extracts failure row with error', () => {
    const row = resultToCsvRow({
      meta: { videoId: 'v2', source: 'history' },
      transcript: null,
      error: 'boom',
    });
    expect(row).toEqual(['v2', 'history', '', '', '', '', '', 'false', '', 'boom']);
  });
});

// ---------------------------------------------------------------------------
// loaders pure helpers
// ---------------------------------------------------------------------------

describe('extractIdFromJsonlRecord', () => {
  test('reads videoId from meta', () => {
    expect(extractIdFromJsonlRecord('{"meta":{"videoId":"abc"}}')).toBe('abc');
  });

  test('reads top-level videoId (legacy shape)', () => {
    expect(extractIdFromJsonlRecord('{"videoId":"xyz"}')).toBe('xyz');
  });

  test('prefers meta.videoId over top-level when both exist', () => {
    expect(extractIdFromJsonlRecord('{"videoId":"top","meta":{"videoId":"nested"}}')).toBe('nested');
  });

  test('returns null for malformed JSON', () => {
    expect(extractIdFromJsonlRecord('not json')).toBeNull();
  });

  test('returns null when record has no recognised id field', () => {
    expect(extractIdFromJsonlRecord('{"foo":"bar"}')).toBeNull();
  });
});

describe('extractVideoIdFromUrl (loose, history loader)', () => {
  test('extracts v param from youtube.com URL', () => {
    expect(extractVideoIdFromUrl('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).toBe(
      'dQw4w9WgXcQ'
    );
  });

  test('extracts path from youtu.be', () => {
    expect(extractVideoIdFromUrl('https://youtu.be/abc')).toBe('abc');
  });

  test('returns null for non-YouTube URL', () => {
    expect(extractVideoIdFromUrl('https://example.com/?v=x')).toBeNull();
  });

  test('returns null for invalid URL', () => {
    expect(extractVideoIdFromUrl('not-a-url')).toBeNull();
  });

  test('does NOT validate length (loose semantics)', () => {
    // history loader keeps whatever YouTube put in `v=`
    expect(extractVideoIdFromUrl('https://www.youtube.com/watch?v=short')).toBe('short');
  });
});

describe('parseCSVLine', () => {
  test('splits on commas', () => {
    expect(parseCSVLine('a,b,c')).toEqual(['a', 'b', 'c']);
  });

  test('handles quoted values containing commas', () => {
    expect(parseCSVLine('"a,b",c')).toEqual(['a,b', 'c']);
  });

  test('handles escaped quotes ""', () => {
    expect(parseCSVLine('"he said ""hi""",end')).toEqual(['he said "hi"', 'end']);
  });

  test('trims whitespace around values', () => {
    expect(parseCSVLine('  a , b ,c')).toEqual(['a', 'b', 'c']);
  });
});

describe('parseCSV', () => {
  test('returns empty when fewer than two lines', () => {
    expect(parseCSV('')).toEqual([]);
    expect(parseCSV('only-header')).toEqual([]);
  });

  test('maps values to header keys', () => {
    const rows = parseCSV('id,name\n1,Alice\n2,Bob');
    expect(rows).toEqual([
      { id: '1', name: 'Alice' },
      { id: '2', name: 'Bob' },
    ]);
  });

  test('fills missing trailing cells with empty string', () => {
    const rows = parseCSV('a,b,c\nx,y');
    expect(rows[0]).toEqual({ a: 'x', b: 'y', c: '' });
  });
});

// ---------------------------------------------------------------------------
// cli + mcp pure helpers
// ---------------------------------------------------------------------------

describe('validateProxyUrl', () => {
  test('accepts http, https, socks4, socks5', () => {
    expect(validateProxyUrl('http://host:8080')).toBe(true);
    expect(validateProxyUrl('https://host:8080')).toBe(true);
    expect(validateProxyUrl('socks4://host:1080')).toBe(true);
    expect(validateProxyUrl('socks5://user:pass@host:1080')).toBe(true);
  });

  test('rejects unsupported schemes', () => {
    expect(validateProxyUrl('ftp://host')).toBe(false);
  });

  test('rejects invalid URLs', () => {
    expect(validateProxyUrl('not-a-url')).toBe(false);
    expect(validateProxyUrl('')).toBe(false);
  });
});

describe('formatTranscriptForCli', () => {
  test('json format returns pretty-printed transcript', () => {
    const out = formatTranscriptForCli(sampleTranscript, 'json', false);
    expect(JSON.parse(out).videoId).toBe('abc12345678');
  });

  test('srt format produces SRT', () => {
    expect(formatTranscriptForCli(sampleTranscript, 'srt', false)).toContain('00:00:00,000');
  });

  test('vtt format starts with WEBVTT', () => {
    expect(formatTranscriptForCli(sampleTranscript, 'vtt', false)).toStartWith('WEBVTT');
  });

  test('default (text) honours includeTimestamps flag', () => {
    expect(formatTranscriptForCli(sampleTranscript, 'text', false)).toBe('Hello world');
    expect(formatTranscriptForCli(sampleTranscript, 'text', true)).toContain('[0:00] Hello world');
  });
});

describe('formatTranscriptForMcp', () => {
  test('segments format returns structured JSON', () => {
    const out = formatTranscriptForMcp(sampleTranscript, 'segments', false);
    const parsed = JSON.parse(out);
    expect(parsed.videoId).toBe('abc12345678');
    expect(parsed.segments).toHaveLength(2);
  });

  test('text format returns plain text', () => {
    expect(formatTranscriptForMcp(sampleTranscript, 'text', false)).toBe('Hello world');
  });

  test('srt/vtt round-trip', () => {
    expect(formatTranscriptForMcp(sampleTranscript, 'srt', false)).toContain('00:00:00,000');
    expect(formatTranscriptForMcp(sampleTranscript, 'vtt', false)).toStartWith('WEBVTT');
  });
});
