/**
 * Output writers for different formats
 */

import { appendTextFile, fileExists, writeTextFile } from '../lib/fs';
import type { OutputOptions, Transcript, TranscriptResult } from '../types';

const CSV_HEADERS = [
  'video_id',
  'source',
  'title',
  'url',
  'channel_name',
  'watched_at',
  'language',
  'is_auto_generated',
  'transcript',
  'error',
] as const;

/**
 * Left-pad a number with zeros. Pure function.
 */
export function pad(num: number, size: number): string {
  return String(num).padStart(size, '0');
}

/**
 * Break seconds into hours/minutes/seconds/milliseconds parts. Pure function.
 */
export function splitTime(seconds: number): {
  hours: number;
  minutes: number;
  seconds: number;
  ms: number;
} {
  return {
    hours: Math.floor(seconds / 3600),
    minutes: Math.floor((seconds % 3600) / 60),
    seconds: Math.floor(seconds % 60),
    ms: Math.floor((seconds % 1) * 1000),
  };
}

/**
 * Format seconds as an SRT timestamp (HH:MM:SS,mmm). Pure function.
 */
export function formatSrtTime(seconds: number): string {
  const t = splitTime(seconds);
  return `${pad(t.hours, 2)}:${pad(t.minutes, 2)}:${pad(t.seconds, 2)},${pad(t.ms, 3)}`;
}

/**
 * Format seconds as a VTT timestamp (HH:MM:SS.mmm). Pure function.
 */
export function formatVttTime(seconds: number): string {
  const t = splitTime(seconds);
  return `${pad(t.hours, 2)}:${pad(t.minutes, 2)}:${pad(t.seconds, 2)}.${pad(t.ms, 3)}`;
}

/**
 * Format seconds as a short timestamp (M:SS) for plain-text output.
 * Pure function.
 */
export function formatTimestamp(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${minutes}:${pad(secs, 2)}`;
}

/**
 * Escape a CSV cell — wraps in quotes and doubles embedded quotes. Pure.
 */
export function escapeCsvCell(value: unknown): string {
  return `"${String(value ?? '').replace(/"/g, '""')}"`;
}

/**
 * Serialize an array of cells as a single CSV row. Pure.
 */
export function rowToCsv(cells: unknown[]): string {
  return cells.map(escapeCsvCell).join(',');
}

/**
 * Convert a TranscriptResult into the CSV cell tuple matching CSV_HEADERS.
 * Pure function.
 */
export function resultToCsvRow(r: TranscriptResult): string[] {
  return [
    r.meta.videoId,
    r.meta.source,
    r.meta.title || '',
    r.meta.url || '',
    r.meta.channel?.name || '',
    r.meta.watchedAt || '',
    r.transcript?.language || '',
    r.transcript?.isAutoGenerated ? 'true' : 'false',
    r.transcript?.text || '',
    r.error || '',
  ];
}

/**
 * Write results to JSONL format (one JSON object per line)
 */
export async function writeJsonl(
  results: TranscriptResult[],
  options: OutputOptions
): Promise<void> {
  const content = `${results.map((r) => JSON.stringify(r)).join('\n')}\n`;
  const write = options.append ? appendTextFile : writeTextFile;
  await write(options.path, content);
}

/**
 * Append a single result to JSONL file (for streaming).
 * Uses atomic append to avoid race conditions in concurrent writes.
 */
export async function appendJsonl(result: TranscriptResult, path: string): Promise<void> {
  await appendTextFile(path, `${JSON.stringify(result)}\n`);
}

/**
 * Write results to CSV format
 */
export async function writeCsv(results: TranscriptResult[], options: OutputOptions): Promise<void> {
  const headerLine = CSV_HEADERS.join(',');
  const rowLines = results.map((r) => rowToCsv(resultToCsvRow(r)));

  if (options.append) {
    // Skip header if file already has content (atomic append)
    const exists = await fileExists(options.path);
    const lines = exists ? rowLines : [headerLine, ...rowLines];
    await appendTextFile(options.path, `${lines.join('\n')}\n`);
  } else {
    await writeTextFile(options.path, `${[headerLine, ...rowLines].join('\n')}\n`);
  }
}

/**
 * Format transcript as SRT subtitle format
 */
export function formatSrt(transcript: Transcript): string {
  const lines: string[] = [];

  transcript.segments.forEach((segment, index) => {
    lines.push(
      String(index + 1),
      `${formatSrtTime(segment.start)} --> ${formatSrtTime(segment.start + segment.duration)}`,
      segment.text,
      ''
    );
  });

  return lines.join('\n');
}

/**
 * Format transcript as VTT subtitle format
 */
export function formatVtt(transcript: Transcript): string {
  const lines: string[] = ['WEBVTT', ''];

  for (const segment of transcript.segments) {
    lines.push(
      `${formatVttTime(segment.start)} --> ${formatVttTime(segment.start + segment.duration)}`,
      segment.text,
      ''
    );
  }

  return lines.join('\n');
}

/**
 * Format transcript as plain text
 */
export function formatText(transcript: Transcript, includeTimestamps = false): string {
  if (!includeTimestamps) return transcript.text;
  return transcript.segments.map((s) => `[${formatTimestamp(s.start)}] ${s.text}`).join('\n');
}
