/**
 * Pure helpers used by the MCP server. Extracted so they can be unit tested
 * without booting the stdio transport.
 */

import { formatSrt, formatText, formatVtt } from './outputs';
import type { Transcript } from './types';

/**
 * Format a transcript for an MCP tool response. Pure function.
 */
export function formatTranscriptForMcp(
  transcript: Transcript,
  format: 'text' | 'segments' | 'srt' | 'vtt',
  includeTimestamps: boolean
): string {
  switch (format) {
    case 'segments':
      return JSON.stringify(
        {
          videoId: transcript.videoId,
          language: transcript.language,
          isAutoGenerated: transcript.isAutoGenerated,
          segments: transcript.segments,
        },
        null,
        2
      );
    case 'srt':
      return formatSrt(transcript);
    case 'vtt':
      return formatVtt(transcript);
    default:
      return formatText(transcript, includeTimestamps);
  }
}

/**
 * Build an MCP text response. Pure function.
 */
export function textResponse(text: string, isError = false) {
  return {
    content: [{ type: 'text' as const, text }],
    ...(isError && { isError: true }),
  };
}

/**
 * Normalise an unknown error into a message string. Pure function.
 */
export function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
